#ifndef LIBDSI_VERSION_H
#define LIBDSI_VERSION_H

#define LIBDSI_MAJOR    0
#define LIBDSI_MINOR    0
#define LIBDSI_REVISION 0
#define LIBDSI_SUFFIX   -SNAPSHOT

#define LIBDSI_VERSION "0.0.0-SNAPSHOT"

#endif // LIBDSI_VERSION_H
