#ifndef DSIWIFI_VERSION_H
#define DSIWIFI_VERSION_H

#define DSIWIFI_MAJOR    0
#define DSIWIFI_MINOR    0
#define DSIWIFI_REVISION 0
#define DSIWIFI_SUFFIX   -SNAPSHOT

#define DSWIFI_VERSION "0.0.0-SNAPSHOT"

#endif // DSIWIFI_VERSION_H
